config/routes.rb
Rails.application.routes.draw do
  resources :testpages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/testpage.rb
class Testpage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/testpages_controller.rb
class TestpagesController < ApplicationController
  before_action :set_testpage, only: [:show, :edit, :update, :destroy]

  # GET /testpages
  # GET /testpages.json
  def index
    @testpages = Testpage.all
  end

  # GET /testpages/1
  # GET /testpages/1.json
  def show
  end

  # GET /testpages/new
  def new
    @testpage = Testpage.new
  end

  # GET /testpages/1/edit
  def edit
  end

  # POST /testpages
  # POST /testpages.json
  def create
    @testpage = Testpage.new(testpage_params)

    respond_to do |format|
      if @testpage.save
        format.html { redirect_to @testpage, notice: 'Testpage was successfully created.' }
        format.json { render :show, status: :created, location: @testpage }
      else
        format.html { render :new }
        format.json { render json: @testpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testpages/1
  # PATCH/PUT /testpages/1.json
  def update
    respond_to do |format|
      if @testpage.update(testpage_params)
        format.html { redirect_to @testpage, notice: 'Testpage was successfully updated.' }
        format.json { render :show, status: :ok, location: @testpage }
      else
        format.html { render :edit }
        format.json { render json: @testpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testpages/1
  # DELETE /testpages/1.json
  def destroy
    @testpage.destroy
    respond_to do |format|
      format.html { redirect_to testpages_url, notice: 'Testpage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testpage
      @testpage = Testpage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testpage_params
      params.require(:testpage).permit(:employeenumber, :employeename)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/testpages_helper.rb
module TestpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testproject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testpages/_form.html.erb
<%= form_with(model: testpage, local: true) do |form| %>
  <% if testpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testpage.errors.count, "error") %> prohibited this testpage from being saved:</h2>

      <ul>
      <% testpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employeenumber %>
    <%= form.number_field :employeenumber, id: :testpage_employeenumber %>
  </div>

  <div class="field">
    <%= form.label :employeename %>
    <%= form.text_field :employeename, id: :testpage_employeename %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/testpages/edit.html.erb
<h1>Editing Testpage</h1>

<%= render 'form', testpage: @testpage %>

<%= link_to 'Show', @testpage %> |
<%= link_to 'Back', testpages_path %>

app/views/testpages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Testpages</h1>

<table>
  <thead>
    <tr>
      <th>Employeenumber</th>
      <th>Employeename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testpages.each do |testpage| %>
      <tr>
        <td><%= testpage.employeenumber %></td>
        <td><%= testpage.employeename %></td>
        <td><%= link_to 'Show', testpage %></td>
        <td><%= link_to 'Edit', edit_testpage_path(testpage) %></td>
        <td><%= link_to 'Destroy', testpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testpage', new_testpage_path %>

app/views/testpages/new.html.erb
<h1>New Testpage</h1>

<%= render 'form', testpage: @testpage %>

<%= link_to 'Back', testpages_path %>

app/views/testpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employeenumber:</strong>
  <%= @testpage.employeenumber %>
</p>

<p>
  <strong>Employeename:</strong>
  <%= @testpage.employeename %>
</p>

<%= link_to 'Edit', edit_testpage_path(@testpage) %> |
<%= link_to 'Back', testpages_path %>